apiVersion: apps/v1
kind: Deployment
metadata:
  name: thangnv-test
  namespace: cpo-dev
spec:
  selector:
    matchLabels:
      app: thangnv-test
  template:
    metadata:
      labels:
        app: thangnv-test
    spec:
      containers:
      - name: thangnv-test
        image: docker.adflex.vn/cpo/addrop_frontend:v2.2.0
        imagePullPolicy: "Always"
        envFrom:
        - configMapRef:
            name: configmap-addrop-frontend-dev
        resources: {}
        ports:
        - containerPort: 80

        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 2000
        #   timeoutSeconds: 20000

        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 300
        #   periodSeconds: 5
        #   timeoutSeconds: 2
      
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 35
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10
        
      imagePullSecrets:
        - name: regcred-adflex
      nodeSelector:
        kubernetes.io/hostname: dev3
---

apiVersion: v1
kind: Service
metadata:
  name: thangnv-test
  namespace: cpo-dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: thangnv-test